### ISSUE TITLE
Wrong output "Failed to enable bluetooth" when enable bluetooth device

### ISSUE THREAD

**Issue by parr0tr1ver** [blueman-project/blueman#1119]
blueman: 2.1.1
BlueZ: 5.50
Distribution: WRLinux
Desktop environment: Xfce

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

I add a debug info in plugins/applet/PowerManager.py: get_bluetooth_status()
  def get_bluetooth_status(self):
        logging.warning("self.current_state: %s" % self.current_state)
        return self.current_state

Steps to reproduce:
1 Start blueman-applet with '--loglevel debug'
2 right click bluetooth-applet icon and disable bluetooth device
3 launch blueman-manager from terminal, and click 'Enable Bluetooth'. It shows error message but the bluetooth device enabled sooner.

sh-5.0# blueman-manager 
blueman-manager version 2.1.1 starting
blueman-manager 09.07.04 
Failed to enable bluetooth

And the applet outputs please see:
https://gist.github.com/parr0tr1ver/c07f9ce43ab19ee63c2d3e7098884a02

get_bluetooth_status() runs before "check     : callbacks done" and then output error message. But the final callback enables the bluetooth device.

Any suggestion is appreciate. Thanks.

**Comment by parr0tr1ver** [comment]
Why the description are missing? :(

**Comment by parr0tr1ver** [comment]
@cschramm what more infomation should I provide, please?

**Comment by cschramm** [comment]
The description was missing. I fixed your markup and can replicate the behavior. Thanks for the report! :slightly_smiling_face:

**Comment by parr0tr1ver** [comment]
@cschramm thanks. I have been reading the source code for a while but didn't get root cause. Do you have any thought how to fix it? Thanks. :)

**Comment by infirit** [comment]
@parr0tr1ver it is a timing issue. Delaying ``if not applet.GetBluetoothStatus():`` in ``check_bluetooth_status`` by a second will solve this. Now, having sleep(1) is a bit ugly so it would probably be nicer to schedule callback and have it check the status every 0.2 seconds or so. But timeout after a few seconds..

If you want to have a go at fixing this look at [Glib.timeout_add](https://lazka.github.io/pgi-docs/#GLib-2.0/functions.html#GLib.timeout_add).

Ideally we also let blueman-manager handle things without exitfunc but this requires a bit more work in ``check_bluetooth_status`` and proper testing.

**Comment by zjeffer** [comment]
Almost 4 years later, This is still happening. I never have bluetooth enabled on boot, so when I start blueman-manager, I click enable bluetooth, and then it exist. This means I always have to start blueman-manager twice.
