### ISSUE TITLE
pygobject: gtk_style_context_get_property: assertion `priv->widget != NULL

### ISSUE THREAD

**Issue by cschramm** [blueman-project/blueman#42]
When an exception occurs in blueman-manager and shall be written into the message area, I get the following error:

    (blueman-manager:19344): Gtk-CRITICAL **: gtk_style_context_get_property: assertion `priv->widget != NULL || priv->widget_path != NULL' failed
    /usr/local/lib/python2.7/dist-packages/blueman/gui/MessageArea.py:171: Warning: /tmp/buildd/glib2.0-2.36.4/./gobject/gtype.c:4239: type id `0' is invalid
      self.show()
    /usr/local/lib/python2.7/dist-packages/blueman/gui/MessageArea.py:171: Warning: can't peek value table for type `<invalid>' which is not currently referenced
      self.show()

**Comment by cschramm** [comment]
@juanitotc reported the same issue using Adwaita in #184. Any more insights?

**Comment by juanitotc** [comment]
$ cat ~/.config/gtk-3.0/settings.ini
[Settings]
gtk-icon-theme-name = gnome
gtk-theme-name = Adwaita

**Comment by infirit** [comment]
This is a bug in pygobject, https://bugzilla.gnome.org/show_bug.cgi?id=678607

**Comment by infirit** [comment]
Can folks try https://github.com/infirit/blueman/commit/b5a8e05e373bcbf4f8a38d359fb0ab943e0f3992 and see if this fixes the problem?

**Comment by juanitotc** [comment]
I tried the patch, but the result is the same.

Note that if I use an x86_64 system with bluez-5, everything works, whereas with an x86 system and bluez-4, I get this failure. There are small differences in the versions of various gtk components, but , apart from bluez, everything else is the same between the x86 and x86_64 setup.

About the only thing I can think of is that notification-daemon might not have been present at compile time on the x86 system.

It looks like blueman is waiting for the answer to a pop-up that never appears?

blueman-applet

--------
notify (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/RecentConns.py:239)
<Device object at 0xb4d15414 (blueman+main+Device+Device at 0x8ac2f80)> <blueman.services.NetworkAccessPoint.NetworkAccessPoint object at 0xb4d17c8c> 00001116-0000-1000-8000-00805f9b34fb 
_________

blueman-manager

_________
fail (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceMenu.py:121)
fail (DBusException(dbus.String(u'Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.'),),) 

(blueman-manager:8794): Gtk-CRITICAL **: gtk_style_context_get_property: assertion 'priv->widget != NULL || priv->widget_path != NULL' failed
/usr/local/lib/python2.7/site-packages/blueman/gui/MessageArea.py:159: Warning: gtype.c:4221: type id '0' is invalid
  self.show()
/usr/local/lib/python2.7/site-packages/blueman/gui/MessageArea.py:159: Warning: can't peek value table for type '<invalid>' which is not currently referenced
  self.show()
Segmentation fault

**Comment by infirit** [comment]
I did not expect it would but there was a little hope Thanks for testing @juanitotc, The EventBox is shown at the bottom of the manager window when error(s) occur. It is not a problem with the notification bubble or notification window.

I run Bluez5 and I also do not see this problem and I find it weird bluez makes the difference :confused:. Below is a simplified version with which everyone can reproduce. What happens is the widget (EventBox) is garbage collected by python as pygobject wrongly does not keep a reference to it. So when we call get_style_context the widget is not longer there and things blow up.

```python
import gi
from gi.repository import Gtk
Gtk.EventBox().get_style_context().get_background_color(Gtk.StateFlags.NORMAL)
```

**Comment by cschramm** [comment]
I think the critical section would be dropped if we migrate to GtkInforBar (#178). I once started working on that in the messagearea branch, but did not continue.

**Comment by infirit** [comment]
Ok, second attempt, please try https://github.com/infirit/blueman/commit/b4572a5c7a3654fd51d15f328c67ca28fa083a4b.

@cschramm yes, because it removes the WidgetFade animation . If this was preserved we probably would run into the same problem.

**Comment by juanitotc** [comment]
I gave it a go with bluez-4, but still no go.

For me, the issue is more that the first pop-up is a gtk box, the second pop-up is a notification-daemon box and there is no third box...

On scanning, the blue progress line gets to 100%, but does not disappear.

On then attempting to pair, blueman-manager segfaults, but on the second attempt it pairs successfully.

Finally when I attempt to set a network access point, nothing happens - it seems to be waiting for a box to pop up, but that does not happen...

scan

_________
Run (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:208)
Function on_request_menu_items on Services Failed 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py", line 212, in Run
    ret = getattr(inst, function)(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/blueman/plugins/manager/Services.py", line 51, in on_request_menu_items
    for service in device.get_services():
  File "/usr/local/lib/python2.7/site-packages/blueman/main/Device.py", line 68, in get_services
    return [service for service in services if service]
  File "/usr/local/lib/python2.7/site-packages/blueman/main/Device.py", line 67, in <genexpr>
    services = (self.get_service(uuid) for uuid in self.UUIDs)
  File "/usr/local/lib/python2.7/site-packages/blueman/main/Device.py", line 64, in get_service
    return cls(self, uuid)
  File "/usr/local/lib/python2.7/site-packages/blueman/Service.py", line 25, in __init__
    proxy = bus.get_object("org.bluez", self.__device.get_object_path())
  File "/usr/local/lib/python2.7/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/local/lib/python2.7/site-packages/dbus/proxies.py", line 244, in __init__
    _dbus_bindings.validate_object_path(object_path)
TypeError: must be string, not None

attempt to pair

err (/usr/local/bin/blueman-manager:230)
(DBusException(dbus.String(u'DBusAuthenticationFailedError: Authentication Failed\n'),),) 

(blueman-manager:13070): Gtk-CRITICAL **: gtk_style_context_get_property: assertion 'priv->widget != NULL || priv->widget_path != NULL' failed
/usr/local/lib/python2.7/site-packages/blueman/gui/MessageArea.py:158: Warning: gtype.c:4221: type id '0' is invalid
  self.show()
/usr/local/lib/python2.7/site-packages/blueman/gui/MessageArea.py:158: Warning: can't peek value table for type '<invalid>' which is not currently referenced
  self.show()
Segmentation fault

Set NAP

_________
fail (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceMenu.py:121)
fail (DBusException(dbus.String(u'Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.'),),) 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/dbus/connection.py", line 607, in msg_reply_handler
    *message.get_args_list()))
  File "/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceMenu.py", line 126, in fail
    self.Blueman.message_area.show_message(_("Connection Failed: ") + e_(str(args[0])))
AttributeError: Blueman instance has no attribute 'message_area'
/usr/local/lib/python2.7/site-packages/gi/overrides/__init__.py:92: Warning: Source ID 2660 was not found when attempting to remove it
  return fn(*args, **kwargs)

**Comment by infirit** [comment]
>For me, the issue is more that the first pop-up is a gtk box, the second pop-up is a notification-daemon box and there is no third box...

-
>On scanning, the blue progress line gets to 100%, but does not disappear.

Can't reproduce both of the above on xubuntu 14.04. Do post the exact steps you do and if you disabled notification daemon use in gsettings org.blueman.general and if one is installed. Also post the full log from blueman applet (this includes startup). Screenshots of the messages would be nice too.

Whatever error I trigger under xubuntu 14.04 that shows up in the MessageArea, I can not reproduce this segfault.

**Comment by juanitotc** [comment]
Using blueman as of today and notification-daemon-3.14.1, libnotify-0.7.5, gtk-3.10.6, bluez-4.101.

Started blueman-applet/manager, set always visible, scanned for devices (this time scanning bar did not stick at 100%), tried to pair with iPhone, popped-up gtk box with pairing pin, clicked on OK, segfault - see blueman-applet and blueman-manager output below.

Then used dconf-editor to set notification-daemon off, restarted blueman-manager.

Attempted to pair with iPhone, popped-up gtk box with pairing pin, clicked on OK and blueman-manager indicated paired. iPhone did not indicated paired, so tapped on device on iPhone, which popped-up notification-daemon trust dialogue (event though notification-daemon disabled in gesettings), clicked on "always accept" and iPhone indicated paired.

Clicked on set as network access point, no pop-up box appeared and eventually blueman-manager segfaults.

I am unable to get a screenshot of the notification-daemon pop-up - it disappears as soon as I try.

----------

$ ps aux | grep noti
24602 tc       /usr/local/lib/notification-daemon/notification-daemon

$ blueman-applet
blueman-applet version 1.99.alpha2 starting
/usr/local/lib/python2.7/site-packages/gi/overrides/__init__.py:175: Warning: The property GSettings:schema is deprecated and shouldn't be used anymore. It will be removed in a future version.
  return super_init_func(self, **new_kwargs)
GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
_________
Load (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:60)
['GameControllerWakelock', 'TransferService', 'StatusIcon', 'StandardItems', 'SerialManager', 'RecentConns', 'NMDUNSupport', 'PPPSupport', 'PowerManager', 'Networking', 'Menu', 'KillSwitch', 'Headset', 'NetUsage', 'DiscvManager', 'DBusService', 'NMPANSupport', 'DhcpClient', 'AuthAgent', 'ShowConnected', 'ExitItem', 'AppIndicator'] 
_________
get_interface_version (/usr/local/lib/python2.7/site-packages/blueman/bluez/BlueZInterface.py:13)
Detected BlueZ 4 
_________
Load (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:60)
Unable to load plugin module AppIndicator
cannot import name AppIndicator3 
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.StatusIcon.StatusIcon'> 
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.DBusService.DBusService'> 
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.GameControllerWakelock.GameControllerWakelock'> 
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.Menu.Menu'> 
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.ExitItem.ExitItem'> 
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.PowerManager.PowerManager'> 
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.NMDUNSupport.NMDUNSupport'> 
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.Headset.Headset'> 
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.DiscvManager.DiscvManager'> 
_________
update_menuitems (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/DiscvManager.py:123)
warning: Adapter is None 
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.TransferService.TransferService'> 
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.KillSwitch.KillSwitch'> 
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.AuthAgent.AuthAgent'> 
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.ShowConnected.ShowConnected'> 
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:133)
Not loading DhcpClient because it's conflict has higher priority 
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.SerialManager.SerialManager'> 
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.RecentConns.RecentConns'> 
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:133)
Not loading PPPSupport because it's conflict has higher priority 
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.StandardItems.StandardItems'> 
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.Networking.Networking'> 
_________
load_nap_settings (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/Networking.py:36)
Loading NAP settings 
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.NMPANSupport.NMPANSupport'> 
_________
io_event (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/KillSwitch.py:72)
killswitch registered 1 
_________
io_event (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/KillSwitch.py:72)
State: True 
_________
UpdatePowerState (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/PowerManager.py:159)
off False 
foff False 
on True 
current state True 
new state True 
_________
on_obex_owner_changed (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/TransferService.py:55)
obex owner changed:  
_________
on_dbus_name_owner_change (/usr/local/bin/blueman-applet:94)
org.bluez owner changed to :1.0 
_________
set_nap (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/Networking.py:65)
set nap False 
_________
register_agent (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/AuthAgent.py:63)
Registering agent 
_________
try_start_ods (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/TransferService.py:49)
Could not acquire obex-data-server org.freedesktop.DBus.Error.ServiceUnknown: The name org.openobex was not provided by any .service files 
_________
initialize (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/RecentConns.py:144)
rebuilding menu 
_________
enumerate_connections (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/ShowConnected.py:50)
Found 0 existing connections 
_________
RequestPowerState (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/PowerManager.py:131)
Requesting True 
_________
on_power_state_change_requested (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/KillSwitch.py:119)
True 
_________
UpdatePowerState (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/PowerManager.py:159)
off False 
foff False 
on True 
current state True 
new state True 
_________
check (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/PowerManager.py:119)
callbacks done 
_________
set_adapter_state (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/PowerManager.py:90)
True 
_________
on_adapter_property_changed (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/DiscvManager.py:96)
prop Discoverable 1 
_________
on_adapter_property_changed (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/DiscvManager.py:96)
prop DiscoverableTimeout 60 
_________
on_adapter_property_changed (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/DiscvManager.py:96)
prop DiscoverableTimeout 0 
_________
on_adapter_property_changed (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/DiscvManager.py:96)
prop Discovering 1 
_________
on_adapter_property_changed (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/DiscvManager.py:96)
prop Discovering 0 
_________
on_adapter_property_changed (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/DiscvManager.py:96)
prop Discovering 1 
_________
on_adapter_property_changed (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/DiscvManager.py:96)
prop Devices dbus.Array([dbus.ObjectPath('/org/bluez/24155/hci0/dev_54_E4_3A_22_48_E9')], signature=dbus.Signature('o'), variant_level=1) 
_________
Release (/usr/local/lib/python2.7/site-packages/blueman/main/applet/BluezAgent.py:142)
Agent.Release 
_________
Cancel (/usr/local/lib/python2.7/site-packages/blueman/main/applet/BluezAgent.py:149)
Agent.Cancel 
_________
__del__ (/usr/local/lib/python2.7/site-packages/blueman/main/applet/BluezAgent.py:139)
Agent on path /org/blueman/agent/temp/54E43A2248E9 deleted 
_________
on_adapter_property_changed (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/DiscvManager.py:96)
prop Devices dbus.Array([], signature=dbus.Signature('o'), variant_level=1) 
_________
on_adapter_property_changed (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/DiscvManager.py:96)
prop Discovering 0 

----------
$ blueman-manager
_________
Load (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:60)
['Services', 'PulseAudioProfile'] 
_________
Load (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:60)
Unable to load plugin module PulseAudioProfile
libpulse.so.0: cannot open shared object file: No such file or directory 
_________
__load_plugin (/usr/local/lib/python2.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.manager.Services.Services'> 
/usr/local/lib/python2.7/site-packages/blueman/gui/MessageArea.py:54: Warning: The property GtkSettings:gtk-button-images is deprecated and shouldn't be used anymore. It will be removed in a future version.
  self.b_more.set_image(im)
blueman-manager version 1.99.alpha2 starting
_________
on_bluez_name_owner_changed (/usr/local/bin/blueman-manager:96)
org.bluez owner changed to  :1.0 
/usr/local/lib/python2.7/site-packages/gi/overrides/__init__.py:175: Warning: The property GSettings:schema is deprecated and shouldn't be used anymore. It will be removed in a future version.
  return super_init_func(self, **new_kwargs)
GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
_________
get_interface_version (/usr/local/lib/python2.7/site-packages/blueman/bluez/BlueZInterface.py:13)
Detected BlueZ 4 
_________
SetAdapter (/usr/local/lib/python2.7/site-packages/blueman/gui/DeviceList.py:269)
 
_________
SetAdapter (/usr/local/lib/python2.7/site-packages/blueman/gui/DeviceList.py:269)
No such adapter 
_________
SetAdapter (/usr/local/lib/python2.7/site-packages/blueman/gui/DeviceList.py:269)
None 
_________
on_adapter_changed (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerToolbar.py:80)
toolbar adapter /org/bluez/24155/hci0 
blueman-adapters version 1.99.alpha2 starting

(blueman-adapters:25001): Gtk-CRITICAL **: gtk_radio_button_set_group: assertion '!g_slist_find (group, radio_button)' failed
org.bluez owner changed to :1.0
_________
on_property_changed (/usr/local/lib/python2.7/site-packages/blueman/gui/DeviceList.py:153)
adapter propery changed Discoverable 1 
value: 1.0
_________
on_property_changed (/usr/local/lib/python2.7/site-packages/blueman/gui/DeviceList.py:153)
adapter propery changed DiscoverableTimeout 60 
value: 0.0
_________
on_property_changed (/usr/local/lib/python2.7/site-packages/blueman/gui/DeviceList.py:153)
adapter propery changed DiscoverableTimeout 0 
_________
on_property_changed (/usr/local/lib/python2.7/site-packages/blueman/gui/DeviceList.py:153)
adapter propery changed Discovering 1 
_________
on_device_found (/usr/local/lib/python2.7/site-packages/blueman/gui/DeviceList.py:133)
Device discovered 54:E4:3A:22:48:E9 
_________
__init__ (/usr/local/lib/python2.7/site-packages/blueman/main/Device.py:26)
caching initial properties 
_________
add_device (/usr/local/lib/python2.7/site-packages/blueman/gui/DeviceList.py:315)
adding new device 
_________
do_cache (/usr/local/lib/python2.7/site-packages/blueman/gui/DeviceList.py:494)
Caching new device 54:E4:3A:22:48:E9 
_________
row_update_event (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceList.py:264)
row update event Fake True 
_________
row_update_event (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceList.py:264)
row update event Trusted 0 
_________
row_update_event (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceList.py:264)
row update event Paired 0 
_________
row_update_event (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceList.py:264)
row update event RSSI -45 
opacity 255
RSSI: -45
_________
on_property_changed (/usr/local/lib/python2.7/site-packages/blueman/gui/DeviceList.py:153)
adapter propery changed Discovering 0 
_________
on_property_changed (/usr/local/lib/python2.7/site-packages/blueman/gui/DeviceList.py:153)
adapter propery changed Discovering 1 
_________
on_device_created (/usr/local/lib/python2.7/site-packages/blueman/gui/DeviceList.py:251)
created /org/bluez/24155/hci0/dev_54_E4_3A_22_48_E9 
_________
__init__ (/usr/local/lib/python2.7/site-packages/blueman/main/Device.py:26)
caching initial properties 
ERROR:dbus.connection:Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/dbus/connection.py", line 230, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/blueman/gui/DeviceList.py", line 256, in on_device_created
    dev = Device(dev)
  File "/usr/local/lib/python2.7/site-packages/blueman/main/Device.py", line 47, in __init__
    self.Properties = self.Device.get_properties()
  File "/usr/local/lib/python2.7/site-packages/blueman/bluez/errors.py", line 148, in warp
    raise parse_dbus_error(exception)
DBusException: org.freedesktop.DBus.Error.UnknownObject: Method "GetProperties" with signature "" on interface "org.bluez.Device" doesn't exist

_________
__del__ (/usr/local/lib/python2.7/site-packages/blueman/main/Device.py:72)
deleting device None 
_________
Destroy (/usr/local/lib/python2.7/site-packages/blueman/main/Device.py:94)
invalidating device None 
_________
err (/usr/local/bin/blueman-manager:230)
(DBusException(dbus.String(u'DBusAuthenticationCanceledError: Authentication Canceled\n'),),) 

(blueman-manager:24994): Gtk-CRITICAL **: gtk_style_context_get_property: assertion 'priv->widget != NULL || priv->widget_path != NULL' failed
/usr/local/lib/python2.7/site-packages/blueman/gui/MessageArea.py:158: Warning: gtype.c:4221: type id '0' is invalid
  self.show()
/usr/local/lib/python2.7/site-packages/blueman/gui/MessageArea.py:158: Warning: can't peek value table for type '<invalid>' which is not currently referenced
  self.show()
Segmentation fault

**Comment by juanitotc** [comment]
I tried again, but this time without notification-daemon being present on the system and with notification-daemon disabled in gsettings.

Following the same sequence as above, this time gtk boxes were popped up for both the pairing pin and for the (iPhone activated) trust dialogue.

When attempting to set the iPhone as a network access point with udhcpc, no pop-ups appear (as per the bluez-5 case, which works, there should be two or three including an "are you sure - yes/no"), blueman-manager appears to get fed-up of waiting and segfaults.

----------

fail (/usr/local/lib/python2.7/site-packages/blueman/gui/manager/ManagerDeviceMenu.py:121)
fail (DBusException(dbus.String(u'Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.'),),) 

(blueman-manager:8199): Gtk-CRITICAL **: gtk_style_context_get_property: assertion 'priv->widget != NULL || priv->widget_path != NULL' failed
/usr/local/lib/python2.7/site-packages/blueman/gui/MessageArea.py:158: Warning: gtype.c:4221: type id '0' is invalid
  self.show()
/usr/local/lib/python2.7/site-packages/blueman/gui/MessageArea.py:158: Warning: can't peek value table for type '<invalid>' which is not currently referenced
  self.show()
Segmentation fault
![blueman_pair](https://cloud.githubusercontent.com/assets/11058217/7427775/cf371966-eff3-11e4-82cc-e298150c8c71.png)
![blueman_trust](https://cloud.githubusercontent.com/assets/11058217/7427776/cf386d7a-eff3-11e4-9a4f-3b2c986b1889.png)

**Comment by cschramm** [comment]
The segfault is the result of the issue discussed here.

If we cannot reproduce and fix this, I think the best we can do is just avoid the critical section, even if we lose some effects for the message area then...

**Comment by cschramm** [comment]
Concerning the notification although the notification-daemon option is turned off: I only found the following notification with an "Always accept" action:

````python
notify_message = (_("Authorization request for:") + "\n%s\n" + _("Service:") + " <b>%s</b>") % (alias, service)
actions = [["always", _("Always accept")],
           ["accept", _("Accept")],
           ["deny", _("Deny")]]
n = Notification(_("Bluetooth Authentication"), notify_message, 0,
                 actions, on_auth_action,
                 pixbuf=get_icon("blueman", 48), status_icon=self.status_icon)
````

Is this what you're seeing?

**Comment by juanitotc** [comment]
I went back to the bluez-5 setup to double-check (with notification-daemon not present and disabled in gsettings) and it looks like I was mistaken, there is no "are you sure - yes/no" type pop-ups, but there are two other ones that do not appear in the bluez4 case
![blueman_nap](https://cloud.githubusercontent.com/assets/11058217/7427911/ee950900-eff6-11e4-809f-089aa440daf7.png)

**Comment by juanitotc** [comment]
BTW, it looks like there's a small non-critical error in the bluez-5 case:

on_network_property_changed (/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/NetUsage.py:371)
UUID 00001116-0000-1000-8000-00805f9b34fb /org/bluez/hci0/dev_54_E4_3A_22_48_E9 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/NetUsage.py", line 120, in poll_stats
    self.update_stats(tx, rx)
  File "/usr/local/lib/python2.7/site-packages/blueman/plugins/applet/NetUsage.py", line 64, in update_stats
    self.general_config["netusage-dev-list"] += [self.device]
  File "/usr/local/lib/python2.7/site-packages/gi/overrides/Gio.py", line 114, in __setitem__
    self.set_value(key, GLib.Variant(type_str, value))
  File "/usr/local/lib/python2.7/site-packages/gi/overrides/GLib.py", line 240, in __new__
    (v, rest_format, _) = creator._create(format_string, [value])
  File "/usr/local/lib/python2.7/site-packages/gi/overrides/GLib.py", line 135, in _create
    return self._create_array(format, args)
  File "/usr/local/lib/python2.7/site-packages/gi/overrides/GLib.py", line 219, in _create_array
    (v, rest_format, _) = self._create(format[1:], args[0][i:])
  File "/usr/local/lib/python2.7/site-packages/gi/overrides/GLib.py", line 123, in _create
    v = constructor(args[0])
TypeError: Must be string, not Device
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

**Comment by infirit** [comment]
>GLib-GIO-Message: Using the 'memory' GSettings backend. Your settings will not be saved or shared with other applications.

@juanitotc, please fix your glib/gsettings install, it is likely this is the reason you get a mix of gtk dialogs and notification bubbles. It sounds like no gsettings backend is installed, usually the backend is dconf.

>BTW, it looks like there's a small non-critical error in the bluez-5 case

Not just bluez5, I'll look into that. I now have a working setup to properly test this.

**Comment by cschramm** [comment]
I just got the crash on an older Debian system (somewhere between wheezy and jessie) and could "fix" it by upgrading gtk, which triggered a lot of other updates as well. Relevant changes are:

Installation of adwaita-icon-theme
gtk3 3.8.6 -> 3.14.5
gdkpixbuf 2.28.2 -> 2.31.1
cairo 1.12.16 -> 1.14.0
pango 1.36.0 -> 1.36.8

**Comment by infirit** [comment]
@cschramm What about the GLib and pygobject version changes? My guess is that bugs got squashed in pygobject.

**Comment by cschramm** [comment]
Nope, no `*py*` changes and glib stayed the same. I can try selective downgrading, but I'm not sure how much the package dependencies allow.

**Comment by infirit** [comment]
>I can try selective downgrading

Not sure how that would help, the segfault is in Gtk so I think it is clear where the issues is. I have 3.10.6 on the xubuntu vm but I do not know (have not checked) how many fixes got backported from newer versions.

**Comment by cschramm** [comment]
@juanitotc What GTK version do you have?

**Comment by cschramm** [comment]
I get the crash with GTK 3.10.2 and below, but do not get it with 3.10.7 and above, so it looks like something got fixed or changed in .3, .4, .5, or .6.

**Comment by infirit** [comment]
@cschramm, @juanitotc is also at 3.10.6 so I think it is definitive now, a bug in Gtk+.

**Comment by cschramm** [comment]
Hm, strange, Debian's 3.10.7-1 did not add any patch and I wonder why your 3.10.6 should have any backport from 3.10.7 (why not just upgrade then). But maybe the issue has something to do with the GTK+ version PLUS the theme or something.

**Comment by cschramm** [comment]
Sooo.... Shall we require a specific version to fix this for blueman? >= 3.10.7?

**Comment by infirit** [comment]
>BTW, it looks like there's a small non-critical error in the bluez-5 case
>>Not just bluez5, I'll look into that. I now have a working setup to properly test this.

@juanitotc, the above is now fixed in master, see https://github.com/blueman-project/blueman/commit/74527f0637a8b11fc09c4bce317908e4d1ddc472

@cschramm, at least mention it as a known issue with Gtk+ <= 3.10.7.  The question is, when 2.0 comes around which major distro will have a problem with the requirement?

**Comment by cschramm** [comment]
Added a note to Dependencies.md.

@juanitotc If the notification-daemon issue persists after fixing your gsettings setup, please open a new thread for that.

**Comment by juanitotc** [comment]
I had gtk-3.10.6 with the bluez-4 setup, but have just updated to 3.14.13 and the segfault has disappeared.

I also added dconf as a blueman dep and the mixed gtk box/notification bubble issue has gone way - my apologies for the noise on this.

All this being said, I still cannot set an iPhone as a NAP with bluez-4 and udhcpc - it's the same error, i.e. no notification boxes and blueman-manager times out - do you want me to start a new issue for this?

**Comment by cschramm** [comment]
> All this being said, I still cannot set an iPhone as a NAP with bluez-4 and udhcpc - it's the same error, i.e. no notification boxes and blueman-manager times out - do you want me to start a new issue for this?

Yes please. This one is so bloated now. :wink:
